Repository Go-Zik/BE-GO-ZIK, pull requests merged in 2023-03, with the labels that each got.

#6 Refactor: 회원가입 카카오 닉네임 랜덤 생성, 회사일 시 입력 가능
  src/main/java/clone/gozik/service/MemberService.java
Labels: documentation

#7 feat : nickname maker & S3 base
  build.gradle
  src/main/java/clone/gozik/S3/S3Config.java
  src/main/java/clone/gozik/S3/S3Uploader.java
  src/main/java/clone/gozik/dto/RequestBoardDto.java
  src/main/java/clone/gozik/service/BoardService.java
Labels: enhancement

#8 mainpage
  src/main/java/clone/gozik/controller/BoardController.java
  src/main/java/clone/gozik/dto/MainBoardResponseDto.java
  src/main/java/clone/gozik/repository/BoardRepository.java
  src/main/java/clone/gozik/service/BoardService.java
Labels: enhancement

#9 feat : DB연결 , CORS, Security 적용
  build.gradle
  src/main/java/clone/gozik/config/WebSecurityConfig.java
  src/main/java/clone/gozik/controller/MemberController.java
  src/main/java/clone/gozik/dto/SecurityExceptionDto.java
  src/main/java/clone/gozik/dto/TestDto.java
  src/main/java/clone/gozik/jwt/JwtAuthFilter.java
  src/main/java/clone/gozik/jwt/JwtUtil.java
  src/main/java/clone/gozik/security/GGAngtong47.java
  src/main/java/clone/gozik/security/UserDetailsImpl.java
  src/main/java/clone/gozik/security/UserDetailsServiceImpl.java
Labels: enhancement

#12 fix : 로그인 시 헤더에 토큰 안보내주는 문제 수정, feat : 이미지 저장기능
  src/main/java/clone/gozik/S3/S3Uploader.java
  src/main/java/clone/gozik/controller/MemberController.java
  src/main/java/clone/gozik/entity/Board.java
  src/main/java/clone/gozik/entity/LogoAndImage.java
  src/main/java/clone/gozik/repository/LogoAndImageRepository.java
  src/main/java/clone/gozik/service/BoardService.java
  src/main/java/clone/gozik/service/MemberService.java
Labels: enhancement

#10 fix: board Create 기능 픽스 & 사용불가능 코드 주석처리
  src/main/java/clone/gozik/dto/AllBoardResponseDto.java
  src/main/java/clone/gozik/dto/RequestBoardDto.java
  src/main/java/clone/gozik/dto/RequestJobDto.java
  src/main/java/clone/gozik/entity/Board.java
  src/main/java/clone/gozik/entity/Job.java
  src/main/java/clone/gozik/jwt/JwtUtil.java
  src/main/java/clone/gozik/repository/JobRepository.java
  src/main/java/clone/gozik/service/BoardService.java
Labels: enhancement

#14 Feat: MessageDto, SuccessCode, ErrorCode구현, 헨들러 구현
  src/main/java/clone/gozik/controller/MemberController.java
  src/main/java/clone/gozik/dto/MessageDto.java
  src/main/java/clone/gozik/entity/ErrorCode.java
  src/main/java/clone/gozik/entity/SuccessCode.java
  src/main/java/clone/gozik/exception/CustomException.java
  src/main/java/clone/gozik/exception/GGANTTONG11.java
  src/main/java/clone/gozik/exception/GlobalExceptionHandler.java
  src/main/java/clone/gozik/security/filter/CustomAccessDeniedHandler.java
  src/main/java/clone/gozik/security/filter/CustomAuthenticationEntryPoint.java
  src/main/java/clone/gozik/service/BoardService.java
  src/main/java/clone/gozik/service/MemberService.java
Labels: enhancement

#15 fix : token관련 username 변수명 email로 변수명 변경 완료
  src/main/java/clone/gozik/jwt/JwtAuthFilter.java
  src/main/java/clone/gozik/jwt/JwtUtil.java
  src/main/java/clone/gozik/security/UserDetailsImpl.java
  src/main/java/clone/gozik/security/UserDetailsServiceImpl.java
Labels: documentation

#18 refactor: 반환타입 변경
  src/main/java/clone/gozik/controller/FavoritesController.java
  src/main/java/clone/gozik/dto/FavoritesResponseDto.java
  src/main/java/clone/gozik/service/FavoritesService.java
Labels: enhancement

#30 fix : 프론트에서 요청과 응답 시 소문자로 통일해야 잘 작동된다고 하셔서 response의 카멜케이스를 다 소문자로 바꿨…
  src/main/java/clone/gozik/dto/OneBoardResponseDto.java
  src/main/java/clone/gozik/dto/OneJobResponseDto.java
Labels: bug
